/**
 * The MIT License (MIT)
 *
 * <p>Copyright (c) 2024 Hypixel, Inc
 *
 * <p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * <p>The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * <p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package io.github.christechs.pithelper.tweaker;

import net.minecraft.launchwrapper.ITweaker;
import net.minecraft.launchwrapper.Launch;
import net.minecraft.launchwrapper.LaunchClassLoader;
import net.minecraftforge.fml.relauncher.CoreModManager;
import org.apache.commons.io.IOUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.*;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.util.List;
import java.util.Objects;
import java.util.Properties;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * A tweaker class to automatically load the hypixel mod api while resolving conflicts from multiple
 * mods providing a copy. This saves users from having to download the mod api separately.
 */
public class HypixelModAPITweaker implements ITweaker {

    public static final String VERSION_NAME;
    public static final long VERSION;
    public static final String BUNDLED_JAR_NAME;

    /**
     * This is the key which is used in the {@link Launch#blackboard} to perform version negotiation.
     *
     * @see #getBlackboardVersion()
     * @see #offerVersionToBlackboard()
     */
    public static final String VERSION_KEY = "net.hypixel.mod-api.version:1";

    private static Logger LOGGER = LogManager.getLogger();

    static {
        // Load version information from the .properties generated by the gradle task
        // generateVersionInfo
        Properties properties = new Properties();
        try {
            properties.load(
                    HypixelModAPITweaker.class.getResourceAsStream("/hypixel-mod-api-bundled.properties"));
        } catch (IOException e) {
            LOGGER.error("Could not load version information for bundled hypixel mod API", e);
        }
        VERSION_NAME = properties.getProperty("version", "1.0.1.2");
        BUNDLED_JAR_NAME = "HypixelModAPI-" + VERSION_NAME + ".jar";
        LOGGER.info("Loaded bundled hypixel mod API version as {}", VERSION_NAME);
        String[] versionComponents = VERSION_NAME.split("\\.");
        assert versionComponents.length == 4;
        // We pack each of the four version components into a long.
        // To do so we use the biggest number that can fit 4 times into a long:
        //noinspection ConstantValue
        assert Math.pow(10000, 4) < Long.MAX_VALUE;
        long version = 0;
        for (int i = 0; i < 4; i++) {
            version *= 10000;
            version += Long.parseLong(versionComponents[i]);
        }
        VERSION = version;
        LOGGER.info("Loaded bundled hypixel mod API numeric version as {}", VERSION);
    }

    private boolean hasOfferedVersion = false;

    /**
     * Get the current version declared on the blackboard. The blackboard allows us to store arbitrary
     * values. We store an int indicating the max version installed.
     *
     * @see #VERSION_KEY
     */
    public static long getBlackboardVersion() {
        Object blackboardVersion = Launch.blackboard.get(VERSION_KEY);
        // In case nobody has declared a version on the blackboard yet, we return an incredibly outdated
        // past version
        if (blackboardVersion == null) return Long.MIN_VALUE;
        // In case we later switch to another version format we declare any non-integer as an incredibly
        // advanced future version
        if (!(blackboardVersion instanceof Long)) return Long.MAX_VALUE;
        return (Long) blackboardVersion;
    }

    private boolean isApiAlreadyInstalled() {
        File modsDir = new File(net.minecraft.launchwrapper.Launch.minecraftHome, "mods");
        if (!modsDir.exists() || !modsDir.isDirectory()) return false;

        File[] jars = modsDir.listFiles((dir, name) -> name.toLowerCase().endsWith(".jar"));
        if (jars == null) return false;

        for (File jar : jars) {
            try (ZipFile zip = new ZipFile(jar)) {
                ZipEntry entry = zip.getEntry("mcmod.info");
                if (entry != null) {
                    try (BufferedReader reader =
                                 new BufferedReader(new InputStreamReader(zip.getInputStream(entry)))) {
                        String line;
                        boolean isApi = false;
                        String foundVersion = "0.0.0.0";

                        while ((line = reader.readLine()) != null) {
                            if (line.contains("\"modid\"") && line.contains("\"hypixel_mod_api\"")) {
                                isApi = true;
                            }
                            if (line.contains("\"version\"")) {
                                String[] parts = line.split("\"");
                                if (parts.length >= 4) foundVersion = parts[3];
                            }
                        }

                        if (isApi) {
                            long standaloneNumericVersion = parseVersion(foundVersion);
                            if (standaloneNumericVersion < VERSION) {
                                LOGGER.warn(
                                        "\n\n[PitHelper] OUTDATED HYPIXEL MOD API DETECTED!\n"
                                                + "Please update '{}' in your mods folder to {} or newer.\n"
                                                + "PitHelper will still load but it might break.",
                                        jar.getName(),
                                        VERSION_NAME);
                            }
                            return true;
                        }
                    }
                }
            } catch (Exception e) {
                if (e instanceof RuntimeException) throw (RuntimeException) e;
            }
        }
        return false;
    }

    private long parseVersion(String versionStr) {
        try {
            String[] components = versionStr.split("\\.");
            long v = 0;
            for (int i = 0; i < 4; i++) {
                v *= 10000;
                if (i < components.length) {
                    v += Long.parseLong(components[i].replaceAll("[^0-9]", ""));
                }
            }
            return v;
        } catch (Exception e) {
            return 0;
        }
    }

    /**
     * Inject our API jar into forge if we are the highest available version.
     *
     * @see #injectAPI()
     */
    private void tryInjectAPI() {
        if (getBlackboardVersion() != VERSION) {
            LOGGER.info("Blackboard version newer than our version {}. Skipping injecting API.", VERSION);
            return;
        }
        if (!hasOfferedVersion) {
            LOGGER.info(
                    "Someone else with the same version number {} offered to inject themselves first. Skipping injecting API.",
                    VERSION);
            return;
        }

        if (isApiAlreadyInstalled()) {
            LOGGER.info(
                    "Found existing 'hypixel_mod_api' ModID in mods folder. Skipping bundled injection.");
            return;
        }

        injectAPI();
    }

    /**
     * Unpacks the actual API file into a temporary folder from where it can be loaded.
     *
     * @return the location of the extracted API
     */
    private File unpackAPI() {
        File extractedFile = new File("hypixel-mod-api/" + BUNDLED_JAR_NAME).getAbsoluteFile();
        LOGGER.info("Unpacking mod API to {}", extractedFile);
        //noinspection ResultOfMethodCallIgnored
        extractedFile.getParentFile().mkdirs();
        try (InputStream bundledJar =
                     Objects.requireNonNull(
                             getClass().getResourceAsStream("/" + BUNDLED_JAR_NAME),
                             "Could not find bundled hypixel mod api");
             OutputStream outputStream = Files.newOutputStream(extractedFile.toPath())) {
            IOUtils.copy(bundledJar, outputStream);
            LOGGER.info("Successfully extracted mod API file");
            return extractedFile;
        } catch (IOException e) {
            LOGGER.error("Could not extract mod API file", e);
            throw new RuntimeException(e);
        }
    }

    /**
     * @return the jar containing this class
     */
    private File getThisJar() {
        URL thisJarURL = getClass().getProtectionDomain().getCodeSource().getLocation();
        if (thisJarURL == null) return null;
        if (!"file".equals(thisJarURL.getProtocol())) return null;
        try {
            return new File(thisJarURL.toURI()).getAbsoluteFile();
        } catch (URISyntaxException ignored) {
        }
        return null;
    }

    /**
     * Inject the API into Forge to be loaded as a mod. This will also extract the JAR.
     */
    private void injectAPI() {
        LOGGER.info("Injecting mod API of version {}", VERSION_NAME);
        try {
            Launch.classLoader.addURL(unpackAPI().toURI().toURL());
            LOGGER.info("Added mod API to classpath");
        } catch (MalformedURLException e) {
            LOGGER.error("Could not add mod API to classpath", e);
        }
    }

    /**
     * Instruct Forge to load the current JAR as a mod. By default, Forge does not load mods if they
     * contain a tweaker, only loading the tweaker instead. This function will remove this JAR from
     * the list of ignored mods and schedule it to be scanned for mods.
     */
    private void allowModLoading() {
        File file = getThisJar();
        if (file != null) {
            if (!CoreModManager.getReparseableCoremods().contains(file.getPath())) {
                CoreModManager.getReparseableCoremods().add(file.getPath());
            }
            CoreModManager.getIgnoredMods().remove(file.getPath());
            LOGGER.info("Re-added mod {} to the mod candidate list.", file);
        } else {
            LOGGER.warn("Did not find JAR including this tweaker, cannot re-add mod.");
        }
    }

    /**
     * Offers our bundled version to the {@link Launch#blackboard}. If there is already a higher
     * version than ours installed then this will not do anything. Otherwise, it will set {@link
     * #hasOfferedVersion} and increment the version in the blackboard.
     *
     * @see #VERSION_KEY
     */
    private void offerVersionToBlackboard() {
        if (getBlackboardVersion() < VERSION) {
            LOGGER.info("Offering newer version {} > {}", VERSION, getBlackboardVersion());
            hasOfferedVersion = true;
            Launch.blackboard.put(VERSION_KEY, VERSION);
        }
    }

    /*
    Below here are all the ITweaker methods. The tweaker methods are executed in rounds.

    1. Run class init and init (constructor) for each tweaker
    2. Run acceptOptions for each tweaker
    3. Run injectIntoClassLoader for each tweaker
    4. If any cascading tweakers have been registered, go back to step 1
    5. After there are no new tweakers after an entire round:
    6. Run getLaunchArguments for each tweaker
    7. Run getLaunchTarget only on the first tweaker found (and execute that class)

    By first offering our version negotiation in acceptOptions or injectIntoClassloader and
    then injection our JARs in getLaunchArguments, we can ensure that every tweaker had time
    to make their version announcement heard.
    */
    @Override
    public void acceptOptions(List<String> args, File gameDir, File assetsDir, String profile) {
        offerVersionToBlackboard();
        allowModLoading();
    }

    @Override
    public void injectIntoClassLoader(LaunchClassLoader classLoader) {
    }

    @Override
    public String getLaunchTarget() {
        return null;
    }

    @Override
    public String[] getLaunchArguments() {
        tryInjectAPI();
        return new String[0];
    }
}
