name: Run Gradle Build
on:
  - push
  - pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks

      - name: Execute Gradle build
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        run: ./gradlew build -PkeyStore="${{ github.workspace }}/keystore.jks" -PkeyStoreAlias="$KEYSTORE_ALIAS" -PkeyStorePass="$KEYSTORE_PASS"

      - name: Upload built mod JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: mod-jar
          path: build/libs/*.jar
